version: '3.8'

services:
  # Define el servicio de tu aplicación Java
  petclinic-app:
    build: . # Le dice a Docker Compose que use el Dockerfile en este mismo directorio.
    ports:
      - "8080:8080" # Mapea el puerto 8080 del contenedor al puerto 8080 de tu máquina.
    depends_on:
      - petclinic-db # Asegura que la base de datos se inicie antes que la aplicación.
    environment:
      # Variables de entorno para la conexión a la base de datos
      - SPRING_DATASOURCE_URL=jdbc:postgresql://petclinic-db:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic

  # Define el servicio de la base de datos PostgreSQL
  petclinic-db:
    image: postgres:14-alpine # Usa una imagen oficial de Postgres, que es ligera.
    environment:
      # Variables de entorno para configurar la base de datos
      - POSTGRES_DB=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_PASSWORD=petclinic
    volumes:
      - db-data:/var/lib/postgresql/data # Persiste los datos de la base de datos en tu máquina.

# Define el volumen para la persistencia de datos
volumes:
  db-data:
